version: 2.1
executors:
  default_image:
    docker:
    - image: cimg/base:2024.01
jobs:
  run-ubuntu-unit-tests:
    environment:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.compiler }}
      FLB_OPT: ${{ matrix.flb_option }}
    docker:
    - image: ubuntu:20.04
    steps:
    - checkout
    - run:
        command: |
          sudo apt-get update
          sudo apt-get install -y gcc-7 g++-7 clang-6.0 libsystemd-dev gcovr libyaml-dev
          sudo ln -s /usr/bin/llvm-symbolizer-6.0 /usr/bin/llvm-symbolizer || true
          echo "CC = $CC, CXX = $CXX, FLB_OPT = $FLB_OPT"
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0
          90
          sudo usermod -a -G systemd-journal $(id -un)
          sudo -E su -p $(id -un) -c "PATH=$PATH ci/scripts/run-unit-tests.sh"
          
  run-macos-unit-tests:
    environment:
      CC: gcc
      CXX: g++
      FLB_OPT: ${{ matrix.flb_option }}
    executor: default_image
    steps:
    - checkout
    - run:
        command: |
          echo "CC = $CC, CXX = $CXX, FLB_OPT = $FLB_OPT"
          brew update
          brew install bison flex openssl || true
          ci/scripts/run-unit-tests.sh
          
  run-all-unit-tests:
    docker:
    - image: cimg/base:2024.01
    steps:
    - checkout
    - run:
        command: |
          exit 1
workflows:
  Run unit tests:
    jobs:
    - run-ubuntu-unit-tests:
        filters:
          branches:
            only:
            - master
    - run-macos-unit-tests
        requires:
        - run-ubuntu-unit-tests
    - run-all-unit-tests:
        requires:
        - run-macos-unit-tests
        - run-ubuntu-unit-tests
